services:
  playwright:
    build: ./
    container_name: playwright-python
    stdin_open: true
    tty: true
    ipc: host
    user: pwuser
    volumes:
      - ./code:/home/pwuser/app
      - /home/ec2-user/.aws:/home/pwuser/.aws
    working_dir: /home/pwuser/app
    command: python app.py
    restart: always
    ports:
      - "5000:5000"